### ISSUE TITLE
Review PF_RING packet capture

### ISSUE THREAD

**Issue by franchoco** [niclabs/ratadns-fievel#19]
If we want faster packet capture we need the PF_RING kernel feature. A starting point is this: http://www.ntop.org/products/packet-capture/pf_ring/

**Comment by franchoco** [comment]
Anything should be said about this, @fmontoto ? (I know we talk about this, but we need a log before closing)

**Comment by fmontoto** [comment]
There are so many thing to say...
Lets link this to an issue related to the stress test. And wait until we have a better understanding of the actual capabilities of the current capture mechanism. Then we should be able to make a decision about this.

**Comment by franchoco** [comment]
Ok, marked as won't fix and closing until we know the actual performance of this module.
