### ISSUE TITLE
Add parallel processing using MCB

### ISSUE THREAD

**Issue by franchoco** [niclabs/ratadns-fievel#21]
As we have the multiple consumer buffer, now we have to use it with multiple threads, one per PreR.

**Comment by emilio-aburto** [comment]
Branch [multithread-prers-21](niclabs/ratadns-fievel/tree/multithread-prers-21) created to work in this issue

**Comment by emilio-aburto** [comment]
Multithread implemented and working, maybe the implementation could be better though.
There's still some memory leaks because of unsolved #30. Should I create a new branch from here or wait the merge and then branch from master?

**Comment by franchoco** [comment]
Wait the merge and branch from master please.

**Comment by franchoco** [comment]
(You should do a pull request of the branch, and assign it to me)

**Comment by emilio-aburto** [comment]
Somehow I managed to forgot about that :|. I can't do it now though.

**Comment by franchoco** [comment]
Solved with #38
