### ISSUE TITLE
Add capability of a custom free/destroy function to objects in MCB

### ISSUE THREAD

**Issue by emilio-aburto** [niclabs/ratadns-fievel#30]
In case of **packet_t** pointers, deallocation doesn't free the inner pointers allocated space, which becomes unreacheable. The solution is to allow a custom function to take care of that, in this case, **packet_dealloc**.

**Comment by franchoco** [comment]
@fmontoto may you do this?

**Comment by fmontoto** [comment]
Sure, could someone  (@emilio-aburto ?) explain how to reproduce the problem or point me to the code?

**Comment by emilio-aburto** [comment]
The problem is exactly [here](https://github.com/niclabs/ratadns-fievel/blob/master/src/multiconsumer_buffer.c#L135), that **free** function may be not enough.

I've no problem adding this feature, but given that it seemed out of place in my current branch, I created a new issue.

**Comment by fmontoto** [comment]
I see, you're right. I think the function must be pass at `mcb_init_buffer` and store the pointer in the `multiconsumer_buffer` struct and use it from there, instead of passing the function each time `mcb_unref` is called.
No sure which one is your branch, but seems like this should have its own branch.

**Comment by emilio-aburto** [comment]
I was thinking instead of changing the existing "constructor" (which may
break some code elsewhere), adding some "set_custom_free" function that
change the default value (free) to another function in a given mcb.
El abr. 7, 2016 16:21, "fmontoto" <notifications@github.com> escribió:

I see, you're right. I think the function must be pass at mcb_init_buffer
and store the pointer in the multiconsumer_buffer struct and use it from
there, instead of passing the function each time mcb_unref is called.
No sure which one is your branch, but seems like this should have its own
branch.

—
You are receiving this because you were assigned.

Reply to this email directly or view it on GitHub
<https://github.com/niclabs/ratadns-fievel/issues/30#issuecomment-207056004>

**Comment by fmontoto** [comment]
This is not an open API, I don't see a problem changing the interface.
I prefer the constructor because it seems more simple to me, so my argument would be that including it in the constructor keeps the API smaller and simpler.
But you'll implement it, it's your call.

**Comment by franchoco** [comment]
I think using the constructor way is better with maintainability in mind. With the parameter in the constructor is harder to forget to free something, as you are force to choose a destroy function.
So, @fmontoto won.
