### ISSUE TITLE
cmake to install and fail

### ISSUE THREAD

**Issue by lmxhappy** [niclabs/ratadns-fievel#41]
Please teach me.
![qq 20160513174400](https://cloud.githubusercontent.com/assets/14830063/15244241/c1da44a0-1932-11e6-8ccd-d3e0a585cea3.png)

**Comment by franchoco** [comment]
Hi!
Our library dependencies are: check, json-c, hiredis, ldns and libpcap. All of these can be found in CentOS repos.

So, to install fievel, go to fievel's folder and do:

$ sudo yum install check-devel json-c-devel hiredis-devel ldns-devel libpcap-devel
$ cmake .
$ make
$ sudo make install

By the way, we need to provide better install instructions 😄 .
Francisco.
