### ISSUE TITLE
to install ratadns fievel

### ISSUE THREAD

**Issue by lmxhappy** [niclabs/ratadns-fievel#42]
hi,
    Yes. You have helped me much. It is successful to install CHECK. However, an error occurs when make is excuted as following.  I checked and found there are two typedef Uint16_Hash_t respectively in hashtable.c and hashtable.h. 
![default](https://cloud.githubusercontent.com/assets/14830063/15265374/eb491104-19b4-11e6-83eb-6bef92e18881.png)
   Then I comment the typedef in hashtable.c and another error appeared like this.
![2](https://cloud.githubusercontent.com/assets/14830063/15265377/f969a776-19b4-11e6-836a-9cc91e81db98.png)

**Comment by franchoco** [comment]
Hi!
Which version of GCC are you using?
That seems to be an old version, so if you tell us the version we may fix that.

**Comment by franchoco** [comment]
This is not an issue now, as the building system is tested through travis and it works in the chosen linux distribution (Ubuntu 12.04 and above, Centos 6 and above). It also works on OS X 10.9 and above.
