### ISSUE TITLE
test memory and CPU usage

### ISSUE THREAD

**Issue by camilog** [niclabs/ratadns-fievel#54]
Is important to know how much memory and CPU is used by fievel, at least in `capture_file` method (which is for now the only one that we can test).

We need to test it in different scenarios: one or several .pcap files, which differ on how many packets per second are processed.

**Comment by eacha** [comment]
We need the originals pcap used in the paper

**Comment by camilog** [comment]
![example.png](https://zube.io/files/niclabs/109ba63e5018c70c38a92b9f41a94af0.png)

This is an example reading a .pcap file three times (in a loop).
It seems that the memory needs to be freed in some time, because if we have larger .pcap files it will fill the entire memory

**Comment by eacha** [comment]
bug confirmed with a 7GB pcap

**Comment by camilog** [comment]
Fixed by #56
